// src/utils/openai.js
export async function generateProfileFromText(text, userInfo) {
  // TODO: Call backend or OpenAI API
  return {
    fullName: userInfo.name,
    shortBio: 'Generated by AI',
    role: userInfo.role,
    education: '',
    topSkills: [],
    tools: [],
    experienceLevel: '',
    careerInterests: [],
    pastProjects: [],
    socials: {},
  };
} 